name: ZJU-OCCS
channels:
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.10
  - pip

  # ---- Core scientific stack ----
  - numpy
  - scipy
  - scikit-learn
  - scikit-optimize

  # ---- Plotting without Qt ----
  - matplotlib-base

  # ---- Web service ----
  - fastapi
  - uvicorn
  - python-multipart

  # ---- Dev / CI tools ----
  - pylint
  - pytest


  # ---- Install your package in editable mode so "import OCCS" works in CI ----
  - pip:
      - -e .
